[package]
name = "rand_server"
authors = ["poly000"]
description = "a tcp server returns random data runs blazingly fast"
version = "0.1.1"
edition = "2018"
license = "MIT"

[dependencies]
rand = "0.8.4"
num_cpus = "1.13.0"
threadpool = "1.8.1"
